CREATE TABLE Owners
(  
   Id INT PRIMARY KEY IDENTITY ,
   Name VARCHAR(50) NOT NULL,
   PhoneNumber VARCHAR(15) NOT NULL,
   Address VARCHAR(50)
)
CREATE TABLE AnimalTypes
(
   Id INT PRIMARY KEY IDENTITY,
   AnimalTypeId VARCHAR(30) NOT NULL
)
CREATE TABLE Cages
(
  Id INT PRIMARY KEY IDENTITY,
  AnimalTypeId INT REFERENCES AnimalTypes(Id) NOT NULL
)
CREATE TABLE Animals
(
   Id INT PRIMARY KEY IDENTITY,
   Name VARCHAR(30) NOT NULL,
   BirthDare DATE NOT NULL,
   OwnerId INT REFERENCES Owners(Id) NOT NULL,
   AnimalTypeId INT REFERENCES AnimalTypes(Id) NOT NULL
)
CREATE TABLE AnimalsCages
(
  CageID INT REFERENCES Cages(Id) NOT NULL,
  AnimalId INT REFERENCES Animals(Id) NOT NULL,
  PRIMARY KEY(CageId,AnimalId)
)
CREATE TABLE VolunteersDepartments
(
  ID INT PRIMARY KEY IDENTITY,
  DepartmentName VARCHAR(30) NOT NULL
)
CREATE TABLE Volunteers
(
  Id INT PRIMARY KEY IDENTITY,
  Name VARCHAR(50) NOT NULL,
  PhoneNumber VARCHAR(15) NOT NULL,
  Address VARCHAR(50),
  AnimalId INT REFERENCES Animals(Id),
  DepartmentId INT REFERENCES VolunteersDepartments NOT NULL
)