CREATE TABLE Users
(
   Id INT PRIMARY KEY IDENTITY,
   UserName VARCHAR(30) UNIQUE NOT NULL,
   Password VARCHAR(50) NOT NULL,
   Name VARCHAR(50),
   Birthdate DATETIME,
   Age INT CHECK(Age> 14 AND Age< 110),
   Email VARCHAR(50) NOT NULL
)
CREATE TABLE Departments
(
   Id INT PRIMARY KEY IDENTITY,
   Name VARCHAR(50) NOT NULL
)
CREATE TABLE Employees
(
   Id INT PRIMARY KEY IDENTITY,
   FirstName VARCHAR(25),
   LastName VARCHAR(25),
   BirthDate DATETIME,
   Age INT CHECK(Age >18 AND Age <110),
   DepartmentId INT REFERENCES Departments(Id)
)
CREATE TABLE Categories
(
  Id INT PRIMARY KEY IDENTITY,
  Name VARCHAR(50) NOT NULL,
  DepartmentId INT REFERENCES Departments(Id) NOT NULL
)
CREATE TABLE Status
(
   Id INT PRIMARY KEY IDENTITY,
   Label VARCHAR(20) NOT NULL
)
CREATE TABLE Reports
(
   Id INT PRIMARY KEY IDENTITY,
   CategoryId INT REFERENCES Categories(Id) NOT NULL,
   StatusId INT REFERENCES Status(Id) NOT NULL,
   OpenDate DATETIME NOT NULL,
   CloseDate DATETIME,
   Description VARCHAR(200) NOT NULL,
   UserId INT REFERENCES Users(Id) NOT NULL,
   EmployeeId INT REFERENCES Employees(Id)
)
